### ISSUE TITLE
Jamming on the "Try Me!" button makes the demo page animation calls stack up

### ISSUE THREAD

**Issue by jeremyckahn** [kbjr/Events.js#2]
On the [demo page](http://www.events-js.com/), you can click on the "Try Me!" button a lot and it makes the animation calls stack.  It should be pretty easy to fix this, I could even do it if the source was available.

Any chance the site source is available somewhere?

**Comment by kbjr** [comment]
No, there isn't a publicly available copy of the source somewhere (although I have considered putting a copy on github). It shouldn't be too hard to fix, I'll look into it. Thanks for mentioning this.

**Comment by kbjr** [comment]
Okay, I just fixed this, and the source for the website is now available at github.com/kbjr/eventsjs-website

**Comment by jeremyckahn** [comment]
Yay!
