### ISSUE TITLE
Invoking an event throws an error on Chrome

### ISSUE THREAD

**Issue by kanduvisla** [kbjr/Events.js#3]
I tried the following code:

```
Events.bind(window, 'resize', function(e){
    console.log('Hello World');
});
Events.invoke(window, 'resize');
```

But Chrome threw the following error:

```
Uncaught [object Object] on events.js:1015
```

Inspecting line 1015 of `events.js` showed me that you called a function called `despatchEvent` instead of `dispatchEvent`. I think this is a typo? Anyway, fixing this (as well as the same typo on line 60), did prevent the script from throwing an error, but the event still wasn't invoked / executed.

**Comment by kbjr** [comment]
Alright, I'll take a look at it.

**Comment by kbjr** [comment]
I'm pretty sure that should fix your problem; please reopen if it does not.
