### ISSUE TITLE
type error if calling Events.unbind before Events.bind

### ISSUE THREAD

**Issue by davidyu** [kbjr/Events.js#7]
On Chrome and Safari (and possibly other browsers, but I haven't tried), with the following snippet of code, I run into a type error.

Code:

```
Events.ready( function() {
  Events.unbind( window, "resize" );
  Events.bind( window, "resize", function() { console.log( "I'm handling it." ); } );
} );
```

Error (Chrome):

```
Uncaught TypeError: Cannot read property 'removeNamespace' of undefined
self2.removeEvent                                            events.js:929
self.unbind                                                  events.js:1203
```

If I call `Events.unbind` after `Events.bind`, this issue no longer occurs.

Also, if I change line 929:

```
        // Remove the namespace
        events[event].removeNamespace(segments);
```

to

```
        // Remove the namespace
        if (events[event] !== undefined) { events[event].removeNamespace(segments); }
```

The error goes away.

Great work on the library!

**Comment by kbjr** [comment]
I didn't rebuild, so the `.min` version won't work.

**Comment by davidyu** [comment]
:+1:

**Comment by davidyu** [comment]
Actually, in a browser, the problem still persists with 1e1bf25, at the same spot:

```
// Remove the namespace
events[event].removeNamespace(segments);
```

Here's an HTML page to repro:

```
<html>
    <head>
        <script src="events.js" type="text/javascript"></script>
    </head>
    <body>
        <script type="text/javascript">
            Events.ready( function() {
                Events.unbind( window, "resize" );
                Events.bind( window, "resize", function() { console.log( "I'm handling it." ); } );
            } );
        </script>
    </body>
</html>
```

The target 'window' has a non-null handler, so it passes your check in `unbind`, but the handler's `events["resize"]` is null and a TypeError is thrown.

 I'll also submit a PR with my workaround if you want to merge.
